### PR TITLE
Add the style for slider-type quiz

### PR DESCRIPTION
**Pull request by vancass**
Add the styling for the slider-type quiz.

### CODE REVIEW

**Comment by yishus** [comment]
slider thumb is stated as non-standard mdn, should we go ahead and use?

if we go this route, we can style for other major browsers also: https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

**Comment by vancass** [comment]
@yishus yes sure let's put the style for ie and firefox in this PR as well

**Comment by vancass** [comment]
Right now it looks like this in IE:

iexplore_2018-11-08_00-03-33


I don't know how to push the dots upwards without affecting Chrome and Firefox 😭

**Comment by vancass** [comment]
Let's ditch IE.

Here's how it looks in Chrome:


Here's for Firefox:

**Pull request merged**
